// =============================================
// JWS: BERLIN RUSH — Cast Characters (Staffel 8)
// =============================================

export const CHARACTERS = [
    {
        id: 'diego',
        name: 'Diego',
        age: 21,
        origin: 'Adlikon ZH',
        bodyColor: '#e67e22',
        hairColor: '#2c1810',
        skinColor: '#c8956c',
        ability: 'triple_jump',
        abilityName: '3-WAY JUMP',
        abilityDesc: 'Dreierkuss-Modus: Dreifach-Sprung möglich',
        maxJumps: 3,
        // Photo asset path (upload from BILDMATERIAL)
        photoSrc: 'assets/sprites/diego.png'
    },
    {
        id: 'nils',
        name: 'Nils',
        age: 23,
        origin: 'Stüsslingen SO',
        bodyColor: '#c0392b',
        hairColor: '#d4b896',
        skinColor: '#f5cba7',
        ability: 'shield',
        abilityName: 'KOMMENTAR-SCHILD',
        abilityDesc: 'Nils\' Aussage schützt vor einem Treffer',
        maxJumps: 1,
        photoSrc: 'assets/sprites/nils.png'
    },
    {
        id: 'anastasia',
        name: 'Anastasia',
        age: 20,
        origin: 'Eschenbach SG',
        bodyColor: '#8e44ad',
        hairColor: '#1a1a1a',
        skinColor: '#fdbcb4',
        ability: 'double_collect',
        abilityName: 'DOPPEL-COLLECT',
        abilityDesc: 'Alle Collectibles zählen doppelt',
        maxJumps: 1,
        photoSrc: 'assets/sprites/anastasia.png'
    },
    {
        id: 'eric',
        name: 'Eric',
        age: 22,
        origin: 'Kriens LU',
        bodyColor: '#2980b9',
        hairColor: '#5c4033',
        skinColor: '#d4a574',
        ability: 'speed_boost',
        abilityName: 'KRANKENWAGEN-SPEED',
        abilityDesc: 'Permanenter Speed-Boost dank Adrenalinstoß',
        maxJumps: 1,
        photoSrc: 'assets/sprites/eric.png'
    },
    {
        id: 'timmo',
        name: 'Timmo',
        age: 21,
        origin: 'Reigoldswil BL',
        bodyColor: '#27ae60',
        hairColor: '#d4b896',
        skinColor: '#f5cba7',
        ability: 'extra_life',
        abilityName: '50-EURO-TROST',
        abilityDesc: 'Startet mit einem Extra-Leben',
        maxJumps: 1,
        photoSrc: 'assets/sprites/timmo.png'
    },
    {
        id: 'alexander',
        name: 'Alexander',
        age: 20,
        origin: 'Balsthal SO',
        bodyColor: '#d35400',
        hairColor: '#2c1810',
        skinColor: '#c8956c',
        ability: 'magnet',
        abilityName: 'CHARME-MAGNET',
        abilityDesc: 'Collectibles werden magnetisch angezogen',
        maxJumps: 1,
        photoSrc: 'assets/sprites/alexander.png'
    },
    {
        id: 'martha',
        name: 'Martha',
        age: 21,
        origin: 'Oltingen BL',
        bodyColor: '#e91e8c',
        hairColor: '#d4b896',
        skinColor: '#fdbcb4',
        ability: 'double_jump',
        abilityName: 'DOPPELSPRUNG',
        abilityDesc: 'Kann einmal in der Luft nochmal springen',
        maxJumps: 2,
        photoSrc: 'assets/sprites/martha.png'
    },
    {
        id: 'lia',
        name: 'Lia',
        age: 20,
        origin: 'Lyss BE',
        bodyColor: '#16a085',
        hairColor: '#1a1a1a',
        skinColor: '#fdbcb4',
        ability: 'slow_obstacles',
        abilityName: 'DRAMA-CHILL',
        abilityDesc: 'Obstacles bewegen sich 15% langsamer',
        maxJumps: 1,
        photoSrc: 'assets/sprites/lia.png'
    },
    {
        id: 'jamie',
        name: 'Jamie',
        age: 22,
        origin: 'Thun BE',
        bodyColor: '#f39c12',
        hairColor: '#6b3a2a',
        skinColor: '#d4a574',
        ability: 'double_jump',
        abilityName: 'CLUB-HOP',
        abilityDesc: 'Doppelsprung für maximale Bewegungsfreiheit',
        maxJumps: 2,
        photoSrc: 'assets/sprites/jamie.png'
    },
    {
        id: 'shinara',
        name: 'Shinara',
        age: 20,
        origin: 'Buchs ZH',
        bodyColor: '#7d3c98',
        hairColor: '#1a1a1a',
        skinColor: '#fdbcb4',
        ability: 'score_boost',
        abilityName: 'STAR-POWER',
        abilityDesc: 'Score-Multiplikator startet bei ×2',
        maxJumps: 1,
        photoSrc: 'assets/sprites/shinara.png'
    },
    {
        id: 'alina',
        name: 'Alina',
        age: 19,
        origin: 'Matzingen TG',
        bodyColor: '#ff69b4',
        hairColor: '#d4b896',
        skinColor: '#fdbcb4',
        ability: 'shield',
        abilityName: 'GEHEIMES LÄCHELN',
        abilityDesc: 'Schützt vor dem ersten Treffer',
        maxJumps: 1,
        photoSrc: 'assets/sprites/alina.png'
    },
    {
        id: 'erica',
        name: 'Erica',
        age: 20,
        origin: 'Hüttwilen TG',
        bodyColor: '#e74c3c',
        hairColor: '#6b3a2a',
        skinColor: '#d4a574',
        ability: 'heart_triple',
        abilityName: 'FLIRT-POWER',
        abilityDesc: 'Herzen geben dreifache Punkte',
        maxJumps: 1,
        photoSrc: 'assets/sprites/erica.png'
    },
    {
        id: 'sandro',
        name: 'Sandro',
        age: 21,
        origin: 'Greifensee ZH',
        bodyColor: '#3498db',
        hairColor: '#2c1810',
        skinColor: '#c8956c',
        ability: 'speed_boost',
        abilityName: 'FLIRT-SPRINT',
        abilityDesc: 'Erhöhte Startgeschwindigkeit',
        maxJumps: 1,
        photoSrc: 'assets/sprites/sandro.png'
    },
    {
        id: 'ermioni',
        name: 'Ermioni',
        age: 20,
        origin: 'Zofingen AG',
        bodyColor: '#1abc9c',
        hairColor: '#1a1a1a',
        skinColor: '#fdbcb4',
        ability: 'shot_double',
        abilityName: 'PARTY-BOOST',
        abilityDesc: 'Shot-Gläser geben doppelte Punkte',
        maxJumps: 1,
        photoSrc: 'assets/sprites/ermioni.png'
    }
];
